train: []
inference:
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)"
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
  - _target_: src.metrics.BeamSearchCERMetric
    name: "CER_(BeamSearch)"
    type: "nolm"
    beam_size: 5
  - _target_: src.metrics.BeamSearchWERMetric
    name: "WER_(BeamSearch)"
    type: "nolm"
    beam_size: 5
